### PR TITLE
Fix/pagination lifetimes

### LINKED ISSUE #246: Expand params with anonymous lifetime is incompatible with 'static lifetime requirement of paginator
After upgrading from 0.14 to 0.15 and attempting to use the new paginator, it seems that the expand parameters with an anonymous lifetime (e.g. `params.expand = ...` where `...` is `&[&str]`) are incompatible with `List<Customer>::paginate`.

```
error[E0759]: `expand` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
   --> crates/my-cool-project/src/lib.rs:224:67
    |
223 |     #[tracing::instrument(err, skip(self))]
    |     --------------------------------------- ...is used here...
224 |     pub async fn find_customer(&self, with_query: &CustomerQuery, expand: &[&str]) -> Result<Customer> {
    |                                                                   ^^^^^^  ------- this data with an anonymous lifetime `'_`...
    |                                                                   |
    |                                                                   ...is used here...
...
264 |                                 .next(&self.client())
    |                                  ---- ...and is required to live as long as `'static` here
    |
note: `'static` lifetime requirement introduced by this bound
   --> /Users/sean/.cargo/git/checkouts/async-stripe-2181100b8e3e802e/d6040d7/src/params.rs:224:39
    |
224 |         P: Clone + Serialize + Send + 'static + std::fmt::Debug,
    |                                       ^^^^^^^
```

Any advice on how to proceed? I suppose I could leak the expand parameters to satisfy a static lifetime, but it's a bit peculiar. Alternatively, I suppose the arguments to `expand` could always be `&'static str`.

### PR DESCRIPTION
**Pull request by arlyon**
Closes #246 which prevents using borrowed params with the paginator api.

Currently planning on reworking this without lifetimes by serializing the params immediately effectively making them owned.

### CODE REVIEW

File: src/client/base/tokio.rs [hunk 1]
```diff
@@ -59,11 +59,11 @@ impl TokioClient {
...
 
-    pub fn execute<T: DeserializeOwned + Send + 'static>(
-        &self,
+    pub fn execute<'a, T: DeserializeOwned + Send + 'a>(
+        &'a self,
         request: Request,
-        strategy: &RequestStrategy,
-    ) -> Response<T> {
+        strategy: &'a RequestStrategy,
+    ) -> Response<'a, T> {
```
Comment (mzeitlin11) [inline src/client/base/tokio.rs:66]: I'm a little confused by the lifetimes here - why is tying the `Response` lifetime tied to the `client` lifetime? Looks like in the function body the `client` gets cloned anyway, so could that `client` just be moved into the future so that no lifetime is needed?

**Comment by mzeitlin11** [comment]
I tried messing around with the lifetimes a bit to avoid the issue mentioned in the comment above but didn't really get anywhere. 

Since we end up cloning the pagination params anyway, what about just leaving the `'static` lifetime on `P` and changing the `Expand` signature? Could use something like `Cow<'static, str>` if still want to support `'static str` without allocation.

**Comment by mzeitlin11** [comment]
Generally a bit wary of the added lifetime parameters, with the example in the comment around `execute`. The extra complexity in the `Response` type used for pagination makes sense, but I wonder if those changes could be isolated to the pagination functionality to not affect the response types for other request types (since IIUC all other API response types should be `'static`.)

I messed around with this code for a bit - some other potential ideas:

- It would be cool to be able to remove `P` from the pagination traits as a way to avoid these lifetimes issues.  As a (slightly ugly) idea of a potential alternative - could immediately serialize the params  into something like `serde_json::Value` then set the cursor into that value whenever needs to be updated. 

- Another alternative to avoid the lifetimes could be to do something like store the cursor and parameters separately, so that the parameters never need to be mutated (so that when `starting_after` is modified, doesn't modify the passed parameters). If parameters aren't mutated, could do something like store the parameters in an `Arc` to avoid lifetimes.

File: src/client/base/tokio.rs (hunk 1 above)
Comment (arlyon) [reply src/client/base/tokio.rs:66]: You are probably correct in questioning this. The PR is a little sloppy at the moment as it took a fair bit of experimentation.

**Comment by arlyon** [comment]
Closing this since it is stalled
