### ISSUE TITLE
Expand params with anonymous lifetime is incompatible with 'static lifetime requirement of paginator

### ISSUE THREAD

**Issue by seanpianka** [arlyon/async-stripe#246]
After upgrading from 0.14 to 0.15 and attempting to use the new paginator, it seems that the expand parameters with an anonymous lifetime (e.g. `params.expand = ...` where `...` is `&[&str]`) are incompatible with `List<Customer>::paginate`.

```
error[E0759]: `expand` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
   --> crates/my-cool-project/src/lib.rs:224:67
    |
223 |     #[tracing::instrument(err, skip(self))]
    |     --------------------------------------- ...is used here...
224 |     pub async fn find_customer(&self, with_query: &CustomerQuery, expand: &[&str]) -> Result<Customer> {
    |                                                                   ^^^^^^  ------- this data with an anonymous lifetime `'_`...
    |                                                                   |
    |                                                                   ...is used here...
...
264 |                                 .next(&self.client())
    |                                  ---- ...and is required to live as long as `'static` here
    |
note: `'static` lifetime requirement introduced by this bound
   --> /Users/sean/.cargo/git/checkouts/async-stripe-2181100b8e3e802e/d6040d7/src/params.rs:224:39
    |
224 |         P: Clone + Serialize + Send + 'static + std::fmt::Debug,
    |                                       ^^^^^^^
```

Any advice on how to proceed? I suppose I could leak the expand parameters to satisfy a static lifetime, but it's a bit peculiar. Alternatively, I suppose the arguments to `expand` could always be `&'static str`.

**Comment by arlyon** [comment]
Hi!

Dynamic expand values is something I didn't consider in the original design but we could probably support it if needed. Can you describe a little more about how you are building the parameter? I've personally only set them statically per-fetch, but I realise now that that use-case is obviously a little inflexible.

**Comment by arlyon** [comment]
For some more context, this issue only appeared because previously pagination completely ignored any params given so I'd say this is at least a step up from that but clearly there is a ways to go.

**Comment by seanpianka** [comment]
Hey there, I appreciate the fast response. I'll work around this by making the input parameters 'static, thanks for the guidance! There's no particular rush from me to support this change, as what you've suggested sounds reasonable enough.

**Comment by seanpianka** [comment]
I suppose the underlying issue here is not that the expand params need to be dynamic, it is that the field of `params` ends with a `'static` lifetime bound in order to paginate. In my case, this is the error:

```rust
error[E0521]: borrowed data escapes outside of associated function
   --> crates/my-cool-crate/src/lib.rs:227:33
    |
224 |     pub async fn find_customer(&self, with_query: &CustomerQuery) -> Result<Customer> {
    |                                       ----------  - let's call the lifetime of this reference `'1`
    |                                       |
    |                                       `with_query` is a reference that is only valid in the associated function body
...
227 |             params.email = Some(email.as_str());
    |                                 ^^^^^^^^^^^^^^
    |                                 |
    |                                 `with_query` escapes the associated function body here
    |                                 argument requires that `'1` must outlive `'static`
```

This works fine when I'm trying list customers:

```rust
    pub async fn find_customer(&self, with_query: &CustomerQuery) -> Result<Customer> {
        let mut params = ListCustomers::new();
        if let CustomerQuery::ByEmailAndId(.., email) = with_query {
            params.email = Some(email.as_str());
        }
        let mut customers =
            Customer::list(&self.client(), &params)
                .await
                .map_err(|e| StripeClientError::StripeError {
                    cause: format!("failed to find customer: {:?}", e),
                })?;
        # ...
```

However, later in the function when paginating through the results, the above issue appears when re-using the same `params` instance:

```rust
                    # ...
                    if customers.has_more {
                        let customer_pagination =
                            customers
                                .paginate(params.clone())
                                .next(&self.client())
                                .await
                                .map_err(|e| StripeClientError::StripeError {
                                    cause: format!("failed to continue paginated listing: {:?}", e),
                                })?;
                        customers = customer_pagination.page;
                    }
```

...is when I run into the above issue where the `params.email` field is made to require a `'static'` lifetime. 

I agree that the expand parameters rarely need to be dynamic values, however the `params` here certainly should be capable of allowing this. 

Any more of your guidance here would be appreciated!

**Comment by arlyon** [comment]
Until I sort out wiring these lifetimes up correctly (thanks again for the report, this is a glaring error) then the suggestions is either downgrade to 0.14 (which has the pagination bug) or leak which is not ideal. Sorry for leaving you in this position, I will prioritise getting a fix out when I am back home.

**Comment by arlyon** [comment]
I have a fix for this (finally). I am going to rebase and merge it this weekend :)

Now all params lifetimes are propagated through the requests properly which allows borrowed params to be used as expected. Will update once I merge.
